#!/usr/bin/env python3
# module REMOVE_OUTPUT
DESCRIPTION = \
"""
    Remove output cells from jupyter python notebook.
    Simplifies version control of jupyter notebooks.\n
"""

import argparse
import io
import os
from shutil import copyfile
import sys

import nbformat

def remove_outputs(nb):
    for cell in nb.cells:
        if cell.cell_type == 'code':
            cell.outputs = []
            cell.execution_count = None

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description = DESCRIPTION,
        epilog = "")
    parser.add_argument('file',
            type=argparse.FileType('r'),
            help='name of jupyter notebook files to be processed', 
            nargs='*') 
    args = parser.parse_args()

    files = args.file
    if files is None:
        sys.exit()

    for file_ in files:
        fname = file_.name
        base, ext = os.path.splitext(fname)
        if ext != '.ipynb':
            print('skipping', fname, base, ext)
            continue

        with io.open(fname, 'r') as f:
            nb = nbformat.read(f, nbformat.NO_CONVERT)

        remove_outputs(nb)
        with io.open(fname, 'w', encoding='utf8') as f:
            nbformat.write(nb, f)
        print("wrote", fname)
